### PR TITLE
Close #8. Fix error handling. Export Client class

### LINKED ISSUE #8: Allow to pass options to cors

### PR DESCRIPTION
**Pull request by TimMikeladze**

### CODE REVIEW

**Comment by davidyaha** [comment]
Would love to get this PR merged. What's left @TimMikeladze?

**Comment by TimMikeladze** [comment]
Just some merge conflicts. I'll get it in to today. Been busy elsewhere.

**Comment by davidyaha** [comment]
Okay no problem, thanks!

**Comment by davidyaha** [comment]
@TimMikeladze Do you mind if I'll merge?

**Comment by TimMikeladze** [comment]
@davidyaha, please do. Thank you!

**Pull request merged**
