### PR TITLE
Feature/oauth callbacks

### PR DESCRIPTION
**Pull request by kamilkisiela**

### CODE REVIEW

**Comment by dotansimha** [comment]
Super useful! With this PR we can give the app the power to manage it's own auth flow.
@kamilkisiela did it because we needed it for using cookies instead of local storage.

**Review by dotansimha — APPROVED** [review]

**Comment by pradel** [comment]
Hey, thanks for the pr! This repo have moved to the main accounts repository, can you please do the pr again there?

**Comment by davidyaha** [comment]
Thanks @kamilkisiela @dotansimha!
Can you also give an example of how to use this new change?

**Comment by kamilkisiela** [comment]
Ref accounts-js/accounts#200

**Pull request closed without merging**
